# Site settings
title:          Yonghwan Kwon
description:    Blogging the digital circuits
url:            "https://yhkwon6658.github.io"
future: true
published: true

# Google Analytics
google_analytics: "G-G87HD3KC9S"

# Author
author:
  name:         
  url:          
  email:        

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         yhkwon6658
